name: Run Tests

on: 
  push: 
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    stepts:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependecies
        run: npm install

      - name: Run unit tests
        run: npm test